### ISSUE TITLE
Add english support

### ISSUE THREAD

**Issue by datagutt** [chloerei/campo1#1]
English support would be nice

**Comment by chloerei** [comment]
Thanks for feedback, will begin processing.

**Comment by chloerei** [comment]
Now can set :locale in url params. like http://codecampo.com/?locale=en . User locale settings will be add in future.

**Comment by chloerei** [comment]
Now can extract locale from HTTP HEADER by iain/http_accept_language. But remove URL params 'locale' support, because it confuse url and search engine.
