### ISSUE TITLE
全新安装之后会报undefined method `layout' for nil:NilClass

### ISSUE THREAD

**Issue by lolychee** [chloerei/campo1#3]
暂时将app/view/layouts/application.haml

line 11  
    - if show_head_html?
      = raw site_config.layout.head_html

line 40

```
      - if show_sidebar_bottom_html?
        = raw site_config.layout.sidebar_bottom_html
```

这两行删去 以解决问题

**Comment by lolychee** [comment]
= = 原来我没初始化数据库

**Comment by chloerei** [comment]
是的，看来这个安装过程不太友好，以后可能会调整下。
