### ISSUE TITLE
搭建时出现问题

### ISSUE THREAD

**Issue by HungYuHei** [chloerei/campo1#4]
执行bundle install时：

Fetching http://github.com/iain/http_accept_language.git
fatal: Unable to find remote helper for 'http'

Git error: command `git clone "http://github.com/iain/http_accept_language.git" "/usr/local/ruby/lib/ruby/gems/1.9.1/cache/bundler/git/http_accept_language-66156b7bd57a56c702f5be22f3581c1eee89a0ff" --bare --no-hardlinks` in directory /home/hungyuhei/openSource/chloerei-campo-ebae89b has failed.

请问怎样解决呢？

**Comment by chloerei** [comment]
什么平台？git是怎么安装的？

curl 装了没？（如果是ubuntu，可以输入curl命令看需要安装哪个包）

**Comment by HungYuHei** [comment]
ubuntu10.10
git是通过源码编译安装的
curl 装了

版本：ruby 1.9.2p0    Rails 3.0.6

**Comment by chloerei** [comment]
试试用Ubuntu的源安装的git，应该是git的问题。

**Comment by HungYuHei** [comment]
可是我一直都在用着Git

**Comment by chloerei** [comment]
编辑 campo / Gemfile

```
gem 'http_accept_language', :git => 'http://github.com/iain/http_accept_language.git'
```

修改成

```
gem 'http_accept_language', :git => 'git://github.com/iain/http_accept_language.git'
```

然后再bundle install看看

**Comment by HungYuHei** [comment]
成功了，谢谢！

是不是因为新版本的Git不支持那个语法？
我的git版本是1.7.4.4

**Comment by chloerei** [comment]
我没有自己编译过git，google了一下说是git编译的时候对http的支持需要一些配置。稍后我找别人的新版本git试试，如果是http支持不好我就改成git的。
