### ISSUE TITLE
How can i manage the Campo

### ISSUE THREAD

**Issue by wikimo** [chloerei/campo1#6]
Is that the admin url like "http://www.xxx.com/admin/",but i don't know the default account of admin.How can i get the admin account. Thanks..

**Comment by chloerei** [comment]
Edit config/campo.yml, add your admin account's email in 'admin_emails' field.

Who's email match the admin_emails list will be a admin account, so remove the unnesssary admin emails.

**Comment by wikimo** [comment]
Thanks for you help...Let me try it...
